# Generated by Django 5.0.2 on 2024-02-20 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('seats', models.PositiveSmallIntegerField(default=60)),
                ('price', models.PositiveBigIntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipolar.flight')),
            ],
            options={
                'unique_together': {('flight', 'departure', 'arrival')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flightSchedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bipolar.flightschedule')),
            ],
        ),
    ]
